<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260308234347 extends AbstractMigration
{
    private array $menuData = [
        ['name' => 'Margarita', 'description' => 'Basic pizza', 'price' => 100, 'picture' => 'margherita.jpg'],
        ['name' => 'Quattro Formaggi', 'description' => 'Delicious four cheese pizza', 'price' => 120, 'picture' => 'quattro.jpg'],
        ['name' => 'Village pizza', 'description' => 'Qiuet and simple life can deliver a lot of delicious tastes', 'price' => 150, 'picture' => 'village.jpg'],
        ['name' => 'Hawaii pizza', 'description' => 'You can love it or hate it', 'price' => 200, 'picture' => 'hawaii.jpg'],
    ];
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(31) NOT NULL, description VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, picture VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "orderr" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(127) NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(511) NOT NULL, quantity INT NOT NULL, placed_at INT NOT NULL, finished_at INT NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5299398CCD7E912 ON "orderr" (menu_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE "orderr" ADD CONSTRAINT FK_F5299398CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        foreach ($this->menuData as $menuDatum) {
            $this->addSql(
                'INSERT INTO menu (name, description, price, picture) VALUES (:name, :description, :price, :picture)',
                $menuDatum
            );
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "orderr" DROP CONSTRAINT FK_F5299398CCD7E912');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE "orderr"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
